// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_math = require("rescript/lib/js/js_math.js");
var Caml_array = require("rescript/lib/js/caml_array.js");

var notes = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G"
];

function reduceFunc(acc, note) {
  var randomValue = Js_math.random_int(0, 6);
  return acc + Caml_array.get(notes, randomValue);
}

function randomNotes(param) {
  return notes.reduce(reduceFunc, notes.join(""));
}

function sortFunc(a, b) {
  return Js_math.random_int(0, 2) - 1 | 0;
}

var randomUniqNotes = notes.sort(sortFunc).join("");

exports.notes = notes;
exports.reduceFunc = reduceFunc;
exports.randomNotes = randomNotes;
exports.sortFunc = sortFunc;
exports.randomUniqNotes = randomUniqNotes;
/* randomUniqNotes Not a pure module */
