// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var RandomNotes = require("./RandomNotes.bs.js");

var notes = RandomNotes.randomNotes(undefined);

console.log(RandomNotes.randomUniqNotes);

var uniqNotes = RandomNotes.randomUniqNotes;

exports.notes = notes;
exports.uniqNotes = uniqNotes;
/* notes Not a pure module */
